fix: add support for sonoma

diff --git a/lazy-connect b/lazy-connect
--- a/lazy-connect
+++ b/lazy-connect
@@ -306,6 +306,80 @@ function _lazy_connect_ventura(){
 EOF
 }
 
+function _lazy_connect_sonoma(){
+  vpn_name=$1
+  osx_vpn_name="${vpn_name/Connect /}"
+  
+  _lazy_connect_get_totp $2
+  local autofill=$3
+
+  if [ -z "$password" ]; then
+    case $TOTP_MODE in
+    oathtool)
+      echo "Error: Unable to generate otp using oathtool."
+      return 1
+      ;;
+    yubikey)
+      echo "Error: No YubiKey found."
+      return 1
+      ;;
+    esac
+  elif [ "$autofill" == "false" ]; then
+    echo -n "$password" | pbcopy
+  fi
+  
+  osascript -l JavaScript > /dev/null <<-EOF
+    function findSwitch(vpnName, areas) {
+      let idx = -1
+      for (let i = 0; i< areas.staticTexts.length; i++) {
+        let text = areas.staticTexts[i]
+        if (text.value() == vpnName) {
+          idx = i
+          break
+        }
+      }
+      return idx/2
+    }
+    function connectVpn(vpnName, password, autofill) {
+      // Reveal System Settings
+      const app = Application("System Settings")
+      app.reveal()
+      const settings = Application("System Events").applicationProcesses.byName("System Settings")
+
+      // Focus on it
+      settings.frontmost = true
+
+      // Wait for System Settings window appearing
+      delay(0.5)
+
+      // Reveal VPN panel
+      settings.menuBars[0].menuBarItems["View"].menus["View"].menuItems["VPN"].click()
+
+      // Wait for panel switching
+      delay(0.5)
+
+      // check the vpn name
+      const areas = settings.windows[0].groups[0].splitterGroups[0].groups[1].groups[0].scrollAreas[0].groups[0]
+      let idx = findSwitch(vpnName, areas)
+      let s = areas.checkboxes[idx]
+      s.click()
+      delay(1)
+      const notif = Application("System Events").applicationProcesses.byName("UserNotificationCenter")
+      if (notif !== undefined && notif !== null) {
+        const w = notif.windows[0]
+        if (w !== undefined && w !== null) {
+          const passwordField = w.textFields[0]
+          passwordField.value = password
+          const okButton = w.buttons[1]
+          okButton.click()
+        }
+      }
+      app.quit()
+    }
+    connectVpn("$osx_vpn_name", "$password", "$autofill")
+EOF
+}
+
 version_lte() {
     [  "$1" = "`echo -e "$1\n$2" | sort -V | head -n1`" ]
 }
@@ -361,14 +435,17 @@ function lazy-connect() {
     fzf --height=10 --ansi --reverse --query "$*" --select-1)
 
   mac_version=$(sw_vers -productVersion)
+  is_less_than_sonoma=$(version_lt $mac_version 14.0 && echo "yes" || echo "no")
   is_less_than_ventura=$(version_lt $mac_version 13.0 && echo "yes" || echo "no")
   is_less_than_mojave=$(version_lt $mac_version 10.14 && echo "yes" || echo "no")
   if [ $is_less_than_mojave = "yes" ]; then
     [ -z "$vpn_name" ] || _lazy_connect "$vpn_name" "$secret" "$autofill"
   elif [ $is_less_than_ventura = "yes" ]; then
     [ -z "$vpn_name" ] || _lazy_connect_mojave "$vpn_name" "$secret" "$autofill"
-  else
+  elif [ $is_less_than_sonoma = "yes" ]; then
     [ -z "$vpn_name" ] || _lazy_connect_ventura "$vpn_name" "$secret" "$autofill"
+  else
+    [ -z "$vpn_name" ] || _lazy_connect_sonoma "$vpn_name" "$secret" "$autofill"
   fi
 
 }
